server:
  port: 18888

management:
  security:
    enabled: false

security:
  basic:
    enabled: false

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rodrigovelaz/application-configuration